{
 "title": "Celery Monitoring",
 "description": "Basic celery monitoring dashboard",
 "tags": [
  "celery",
  "monitoring"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Celery Worker Count",
   "type": "gauge",
   "description": "This panel shows status of celery workers. 1 = online, 0 = offline.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(celery_worker_up{job=\"kubernetes-pods\", namespace=\"workshop\"} == 1)",
     "legendFormat": "Workers"
    }
   ]
  },
  {
   "title": "Celery Worker Time Series",
   "type": "timeseries",
   "description": "This panel shows status of celery workers over time.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(celery_worker_up{job=\"kubernetes-pods\", namespace=\"workshop\"})",
     "legendFormat": "Online Workers"
    }
   ]
  },
  {
   "title": "Task Active",
   "type": "stat",
   "description": "Active tasks by queue",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(celery_worker_tasks_active{job=\"kubernetes-pods\", namespace=\"workshop\"})",
     "legendFormat": "Active Tasks"
    }
   ]
  },
  {
   "title": "Average Runtime for Tasks [5m]",
   "type": "stat",
   "description": "Average task runtime",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(celery_task_runtime_sum{job=\"kubernetes-pods\", namespace=\"workshop\"}[5m])) / sum(rate(celery_task_runtime_count{job=\"kubernetes-pods\", namespace=\"workshop\"}[5m])) > 0",
     "legendFormat": "Average Runtime"
    }
   ]
  },
  {
   "title": "Queue Size by Queue Name",
   "type": "timeseries",
   "description": "Queue size over time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(celery_queue_length{job=\"kubernetes-pods\", namespace=\"workshop\"}) by (queue_name)",
     "legendFormat": "{{ queue_name }}"
    }
   ]
  },
  {
   "title": "Task Status Overview",
   "type": "timeseries",
   "description": "Task status overview",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(celery_task_succeeded_total{job=\"kubernetes-pods\", namespace=\"workshop\"}[$__rate_interval]))",
     "legendFormat": "Succeeded"
    },
    {
     "expr": "sum(increase(celery_task_failed_total{job=\"kubernetes-pods\", namespace=\"workshop\"}[$__rate_interval]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(increase(celery_task_sent_total{job=\"kubernetes-pods\", namespace=\"workshop\"}[$__rate_interval]))",
     "legendFormat": "Sent"
    },
    {
     "expr": "sum(increase(celery_task_received_total{job=\"kubernetes-pods\", namespace=\"workshop\"}[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(increase(celery_task_retried_total{job=\"kubernetes-pods\", namespace=\"workshop\"}[$__rate_interval]))",
     "legendFormat": "Retried"
    }
   ]
  },
  {
   "title": "Worker Status",
   "type": "stat",
   "description": "This panel shows worker status (online/offline)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "celery_worker_up{job=\"kubernetes-pods\", namespace=\"workshop\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Active Tasks by Worker",
   "type": "timeseries",
   "description": "Active tasks by worker",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "celery_worker_tasks_active{job=\"kubernetes-pods\", namespace=\"workshop\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Task Success/Failure by Name",
   "type": "timeseries",
   "description": "Success/failure rate by task",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(celery_task_succeeded_total{job=\"kubernetes-pods\", namespace=\"workshop\"}) by (name)",
     "legendFormat": "{{name}} - succeeded"
    },
    {
     "expr": "sum(celery_task_failed_total{job=\"kubernetes-pods\", namespace=\"workshop\"}) by (name)",
     "legendFormat": "{{name}} - failed"
    }
   ]
  },
  {
   "title": "Task Success Rate (per second)",
   "type": "timeseries",
   "description": "Task Success Rate (operations per second)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(irate(celery_task_succeeded_total{job=\"kubernetes-pods\", namespace=\"workshop\"}[30s])) by (name)",
     "legendFormat": "{{name}} - rate"
    }
   ]
  }
 ]
}