# Prometheus configuration for WaveSpeed Workshop

## Global settings
global:
  evaluation_interval: 30s
  scrape_interval: 10s
  scrape_timeout: 10s

## Server configuration
server:
  persistentVolume:
    enabled: true
    size: 8Gi
  resources:
    limits:
      memory: 1Gi
      cpu: 500m
    requests:
      memory: 512Mi
      cpu: 200m
  # Ensure no authentication is enabled
  enableAdminApi: true

## Configure Alertmanager
alertmanager:
  enabled: true
  persistentVolume:
    enabled: true
    size: 2Gi

## Disable PodSecurityPolicy (not supported in newer Kubernetes versions)
rbac:
  create: true
  pspEnabled: false

## Prometheus service monitors
serviceMonitors:
  # Redis monitoring
  - name: redis
    enabled: true
    selector:
      matchLabels:
        app.kubernetes.io/name: redis
    namespaceSelector:
      matchNames:
        - workshop
    endpoints:
      - port: metrics
        interval: 10s
        path: /metrics

## Additional scrape configs for Redis metrics
extraScrapeConfigs: |
  - job_name: 'redis-metrics'
    scrape_interval: 10s
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
            - workshop
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
        regex: redis
        action: keep
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        regex: metrics
        action: keep
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - source_labels: [__meta_kubernetes_service_name]
        target_label: service
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod

## Prometheus alerting rules
serverFiles:
  alerting_rules.yml:
    groups:
      - name: redis-alerts
        rules:
          - alert: RedisDown
            expr: redis_up == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Redis instance is down"
              description: "Redis instance {{ $labels.instance }} is down"
          - alert: RedisHighMemory
            expr: redis_memory_used_bytes / redis_total_system_memory_bytes * 100 > 80
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "Redis high memory usage"
              description: "Redis instance {{ $labels.instance }} memory usage is over 80%" 