{{- if .Values.celery.worker.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "celery-app.fullname" . }}-{{ .Values.celery.worker.name | default "worker" }}
  labels:
    {{- include "celery-app.labels" . | nindent 4 }}
    component: worker
    queue: default
spec:
  {{- if not .Values.celery.worker.autoscaling.enabled }}
  replicas: {{ .Values.celery.worker.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "celery-app.selectorLabels" . | nindent 6 }}
      component: worker
      queue: default
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
      labels:
        {{- include "celery-app.selectorLabels" . | nindent 8 }}
        component: worker
        queue: default
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "celery-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-{{ .Values.celery.worker.name | default "worker" }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python"]
          args: ["-m", "src.worker"]
          ports:
            - name: metrics
              containerPort: 9090
              protocol: TCP
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }} 