FROM nginx:alpine

# Copy static files to Nginx server
COPY static/ /usr/share/nginx/html/

# Copy custom NGINX config if needed
# COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"] 