{{- if .Values.static.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "visualize.fullname" . }}-static
  labels:
    {{- include "visualize.labels" . | nindent 4 }}
    app.kubernetes.io/component: static
spec:
  type: {{ .Values.static.service.type }}
  ports:
    - port: {{ .Values.static.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "visualize.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: static
{{- end }} 