{{- if .Values.websocket.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "visualize.fullname" . }}-websocket
  labels:
    {{- include "visualize.labels" . | nindent 4 }}
    app.kubernetes.io/component: websocket
spec:
  replicas: {{ .Values.websocket.replicaCount }}
  selector:
    matchLabels:
      {{- include "visualize.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: websocket
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "visualize.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: websocket
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "visualize.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-websocket
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.websocket.image.repository }}:{{ .Values.websocket.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: ws
              containerPort: {{ .Values.websocket.service.wsPort }}
              protocol: TCP
            - name: http
              containerPort: {{ .Values.websocket.service.httpPort }}
              protocol: TCP
          env:
            - name: WS_PORT
              value: "{{ .Values.websocket.service.wsPort }}"
            - name: HTTP_PORT
              value: "{{ .Values.websocket.service.httpPort }}"
            - name: HOST
              value: "0.0.0.0"
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.websocket.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }} 