apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inference-balancer.fullname" . }}-flux-b-token
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "inference-balancer.labels" . | nindent 4 }}
    app.kubernetes.io/component: flux-b
data:
  token.conf: |
    proxy_set_header Authorization "Bearer {{ .Values.fluxServices.a.datacrunch.bearerToken }}"; 