apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inference-balancer.fullname" . }}-log-exporter-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "inference-balancer.labels" . | nindent 4 }}
    app.kubernetes.io/component: log-metrics-exporter
data:
  promtail-config.yaml: |
    server:
      http_listen_port: 9090
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      # Dummy client to satisfy Promtail requirement
      - url: http://dummy-client/dummy
        batchwait: 0s
        batchsize: 0
        tenant_id: ""
        external_labels: {}

    scrape_configs:
      - job_name: nginx_logs
        static_configs:
          - targets:
              - localhost
            labels:
              job: nginx_logs
              __path__: /var/log/nginx/access.log
        pipeline_stages:
          - json:
              expressions:
                timestamp: timestamp
                remote_addr: remote_addr
                request: request
                status: status
                bytes_sent: bytes_sent
                upstream_service: upstream_service
                request_time: request_time
                upstream_connect_time: upstream_connect_time
                upstream_header_time: upstream_header_time
                upstream_response_time: upstream_response_time
                upstream_addr: upstream_addr
          - metrics:
              request_count:
                type: Counter
                description: "Count of requests by upstream service"
                config:
                  action: inc
                  match_all: true
                  labels:
                    upstream_service: "upstream_service"
                    status: "status"
              request_duration_seconds:
                type: Histogram
                description: "Duration of requests in seconds"
                config:
                  buckets: [0.001, 0.01, 0.1, 0.5, 1, 2, 5, 10]
                  value: "request_time"
                  action: observe
                  match_all: true
                  labels:
                    upstream_service: "upstream_service"
                    status: "status"
              upstream_response_time_seconds:
                type: Histogram
                description: "Upstream response time in seconds"
                config:
                  buckets: [0.001, 0.01, 0.1, 0.5, 1, 2, 5, 10]
                  value: "upstream_response_time"
                  action: observe
                  match_all: true
                  labels:
                    upstream_service: "upstream_service"
                    status: "status" 