apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "inference-balancer.fullname" . }}-nginx-logs
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "inference-balancer.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi 