  # Prometheus for monitoring
  - name: prometheus
    namespace: monitoring
    chart: prometheus-community/prometheus
    version: "19.0.0"  # Updated to a more recent version
    labels:
      category: scaffolding
    values:
      - values/prometheus-values.yaml
  
  # Grafana for visualization
  - name: grafana
    namespace: monitoring
    chart: grafana/grafana
    version: "6.50.7"  # Updated to a more recent version
    labels:
