{{- if .Values.celery.api.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "celery-app.fullname" . }}-nginx-config
  labels:
    {{- include "celery-app.labels" . | nindent 4 }}
data:
  nginx.conf: |-
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log;
    pid /run/nginx.pid;

    events {
        worker_connections 1024;
    }

    http {
        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

        access_log /var/log/nginx/access.log main;

        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        server {
            listen 80;
            server_name _;

            # Health check endpoint for liveness and readiness probes
            location /health {
                access_log off;
                add_header Content-Type text/plain;
                return 200 'OK';
            }

            # Proxy all other requests to the FastAPI application on the same pod
            location / {
                proxy_pass http://127.0.0.1:{{ .Values.celery.api.port }};
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }
{{- end }} 