apiVersion: v1
kind: Service
metadata:
  name: {{ include "inference-balancer.fullname" . }}-main
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "inference-balancer.labels" . | nindent 4 }}
    app.kubernetes.io/component: main-loadbalancer
spec:
  type: {{ .Values.mainLoadBalancer.service.type }}
  ports:
    - port: {{ .Values.mainLoadBalancer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "inference-balancer.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: main-loadbalancer 