apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "inference-balancer.fullname" . }}-proxy-a
  labels:
    {{- include "inference-balancer.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxy-a
spec:
  replicas: {{ .Values.proxyA.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "inference-balancer.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: proxy-a
  template:
    metadata:
      labels:
        {{- include "inference-balancer.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: proxy-a
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "inference-balancer.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}-proxy-a
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.proxyA.resources | default dict | nindent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "inference-balancer.fullname" . }}-proxy-a-config 