apiVersion: v1
kind: Service
metadata:
  name: {{ include "inference-balancer.fullname" . }}-proxy-a
  labels:
    {{- include "inference-balancer.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxy-a
spec:
  type: {{ .Values.proxyA.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.proxyA.service.port | default 80 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "inference-balancer.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: proxy-a 