apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-loadtest
  namespace: workshop
  labels:
    app: celery-loadtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-loadtest
  template:
    metadata:
      labels:
        app: celery-loadtest
    spec:
      containers:
      - name: locust
        image: celery-loadtest:latest
        imagePullPolicy: Never  # Use local image
        env:
        - name: LOCUST_HOST
          value: "http://celery-app-api"
        - name: LOCUST_USERS
          value: "500"
        - name: LOCUST_SPAWN_RATE
          value: "50"
        - name: LOCUST_RUN_TIME
          value: "48h"  # Run for 48 hours continuously
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: celery-loadtest
  namespace: workshop
  labels:
    app: celery-loadtest
spec:
  ports:
  - port: 8089
    targetPort: 8089
    protocol: TCP
    name: web
  selector:
    app: celery-loadtest
  type: ClusterIP 